### ISSUE TITLE
west update fails if app-path is more than 1 folder deep

### ISSUE THREAD

**Issue by DavidVanKampen-eaton** [zephyrproject-rtos/action-zephyr-setup#20]
If the `app-path` parameter, where the `west.yml` resides, is more than 1 folder deep, then this action fails when running `west update` because it says it can't find the workspace.

For example, if app-path is: `folder1/folder2/`, like so: 

```yaml
- name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: folder1/folder2/  # note - it does not seem to help if there is or is not a trailing slash here
        sdk-version: 0.16.0
```

then the build output looks like the following:

```
Run west init -l folder1/folder2/ --mf west.yml
  
=== Initializing from existing manifest repository folder2
--- Creating WORKSPACE_ROOT/folder1/.west and local configuration file
=== Initialized. Now run "west update" inside WORKSPACE_ROOT/folder1.
FATAL ERROR: no west workspace found from "WORKSPACE_ROOT"; "west update" requires one.
Things to try:
  - Change directory to somewhere inside a west workspace and retry.
  - Set ZEPHYR_BASE to a zephyr repository path in a west workspace.
  - Run "west init" to set up a workspace here.
  - Run "west init -h" for additional information.
 ```
note above WORKSPACE_ROOT is just the github action root working directory.

 It seems the `west update` call should happen at `app-path`, or its parent.

**Comment by fabiobaltieri** [comment]
@DavidVanKampen-eaton yeah, `west init` creates the workspace on the last directory and then everything falls apart. I tried to set `ZEPHYR_BASE` in the manifest but then it's a bit tricky to find out the requirement file so I propose to restrict `app-path` to a single directory and add a `base-path` variable with any prefix that can be used for all steps that depends on the application path.

I tested it on one of my test repo but could you check if it works for you? You can instantiate it like:

```
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@refs/pull/21/head
        with:
          base-path: the/app/prefix
          app-path: app
          toolchains: arm-zephyr-eabi
```

(which would look for a manifest in `the/app/prefix/app` and do all other operations in `the/app/prefix`)

The `refs/pull/21/head` would be for a single test, if you confirm it works I'll have the change reviewed, merged and pushed on an updated `v1` tag
